version: '3.8'

services:
  config-server:
    build:
      context: ../services/config-server
    image: artemis/config-server:latest
    container_name: config-server
    ports:
      - "6090:6090"
    env_file:
      - config-server.env
    networks:
      - artemis-net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:6090/actuator/health" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  discovery-server:
    build:
      context: ../services/discovery-server
    image: artemis/discovery-server:latest
    container_name: discovery-server
    ports:
      - "6091:6091"  # updated port
    env_file:
      - discovery-server.env
    depends_on:
      config-server:
        condition: service_healthy
    networks:
      - artemis-net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:6091/actuator/health" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  api-gateway:
    build:
      context: ../services/api-gateway
    image: artemis/api-gateway:latest
    container_name: api-gateway
    ports:
      - "6092:6092"  # updated port
    env_file:
      - api-gateway.env
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    networks:
      - artemis-net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:6092/actuator/health" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
  auth-service:
    build:
      context: ../services/auth-service
    image: artemis/auth-service:latest
    container_name: auth-service
    ports:
      - "6094:6094"  # updated port
    env_file:
      - auth-service.env
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
      api-gateway:
        condition: service_healthy
    networks:
      - artemis-net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:6094/actuator/health" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
  account-management:
    build:
      context: ../services/account-management
    image: artemis/account-management:latest
    container_name: account-management
    ports:
      - "6093:6093"  # updated port
    env_file:
      - account-management.env
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
      api-gateway:
        condition: service_healthy
    networks:
      - artemis-net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:6093/actuator/health" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
  customer-management:
    build:
      context: ../services/customer-management
    image: artemis/customer-management:latest
    container_name: customer-management
    ports:
      - "6095:6095"  # updated port
    env_file:
      - customer-management.env
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
      api-gateway:
        condition: service_healthy
    networks:
      - artemis-net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:6095/actuator/health" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
  ledger-service:
    build:
      context: ../services/ledger-service
    image: artemis/ledger-service:latest
    container_name: ledger-service
    ports:
      - "6096:6096"  # updated port
    env_file:
      - ledger-service.env
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
      api-gateway:
        condition: service_healthy
    networks:
      - artemis-net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:6096/actuator/health" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

networks:
  artemis-net:
    external: true